### ISSUE TITLE
Possible NumPy-free implementation

### ISSUE THREAD

**Issue by DonaldTsang** [dstein64/LC4#2]
Is it possible to create an implementation where it is pure Python?

**Comment by dstein64** [comment]
@DonaldTsang, a version without Numpy is feasible, but a Numpy-version is simpler because of its matrix operations. A numpy version is also faster, but that wasn't a consideration.

Can you elaborate on your interest in a version without Numpy? My expectation is that in most environments where Python can be installed, numpy can also be installed.

**Comment by DonaldTsang** [comment]
@dstein64 I was thinking of a external dependency-free version of LC4, which could be very useful for in cases where import libraries are unworkable.

**Comment by dstein64** [comment]
Hi @DonaldTsang, I see the benefits of a dependency-free library. However, without any specific scenarios that require it, I don't think it's worth the effort. Virtual environments (virtualenv, pipenv, conda env) make it easy to have self-contained environments, where required dependencies can be installed without interfering with the system or other environments.
